version: "3"
services:
  mongo:
    image: mongo
  server:
    build: ./server
    depends_on:
      - mongo
    ports:
      - "3012:3012"
  web:
    build: ./web-app
    depends_on:
      - server
    ports:
      - "3008:3008"